name: Workflow with JSON Step Names

on:
  workflow_dispatch:
    inputs:
      revision:
        required: true
        type: string    
      application_id:
        description: 'Application ID'
        required: true
        type: string
      environment_id:
        description: 'Environment ID'
        required: true
        type: string
      environment_name:
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set revision
        run: |
          if [ "${{ inputs.revision }}" == "HEAD" ]; then
            echo "REVISION=${{ github.sha }}" >> "$GITHUB_ENV"
          else
            echo "REVISION=${{ inputs.revision }}" >> "$GITHUB_ENV"
          fi
    
      - name: '{ "application_id": "${{ inputs.application_id }}", "environment_id": "${{ inputs.environment_id }}", "revision": "${{env.REVISION}}" }'
        id: deploy
        run: echo "Running deployment..."

run-name: '${{ inputs.revision == ''HEAD'' && format(''{0}: revision {1}'', inputs.environment_name, github.sha) || format(''{0}: revision {1}'', inputs.environment_name, inputs.revision) }}'
